// Database các nhà hàng
const restaurants = {
    "fries_vietnam": {
        name: "Fries Vietnam - Thế Giới Khoai Tây Chiên",
        address: "89 Nguyễn Thái Học, Phường Cầu Ông Lãnh, Quận 1, TP. HCM",
        rating: 4.5,
        time: "10:00 - 21:30",
        priceRange: "60,000đ - 160,000đ",
        logo: "img/Logo/logo1.png",
        bannerBg: "img/Background-shop/bg1.jpg", // Ảnh nền banner (nếu muốn thay đổi)
        menu: [
            { id: "fries_001", name: "Khoai Lõi Vai Bò Mỹ Xốt Phômai", price: 155000, img: "img/menu/fries_001.jpg" },
            { id: "fries_002", name: "Khoai Lõi Vai Bò Mỹ Xốt Tiêu Đen", price: 145000, img: "img/menu/fries_002.jpg" },
            { id: "fries_003", name: "Khoai Lõi Vai Bò Mỹ Xốt Nấm", price: 155000, img: "img/menu/fries_003.jpg" },
            { id: "fries_005", name: "Khoai Bò Bằm Cheddar", price: 79000, img: "img/menu/fries_005.jpg" },
            { id: "fries_006", name: "Khoai Cá Hồi Nướng Mật Ong", price: 87000, img: "img/menu/fries_006.jpg" },
            { id: "fries_007", name: "Khoai Thịt Viên Phô Mai", price: 75000, img: "img/menu/fries_007.jpg" },
            { id: "fries_008", name: "Khoai Tôm Cocktail", price: 79000, img: "img/menu/fries_008.jpg" },
            { id: "fries_009", name: "Khoai Bò Hầm Xé Sợi", price: 89000, img: "img/menu/fries_009.jpg" },
            { id: "fries_010", name: "Nui Bò Băm Cay", price: 75000, img: "img/menu/fries_010.jpg" },
            { id: "fries_011", name: "Nui Đúc Lò Tôm Truffle", price: 79000, img: "img/menu/fries_011.jpg" },
            { id: "fries_012", name: "Nui Phômai Đúc Lò Thịt Xông Khói", price: 75000, img: "img/menu/fries_012.jpg" },
            { id: "fries_004", name: "Mì Ý Cua Xốt Kem ", price: 97000, img: "img/menu/fries_004.jpg" },
            { id: "fries_013", name: "Mì Ý Tôm Chua Cay", price: 109000, img: "img/menu/fries_013.jpg" },
            { id: "fries_014", name: "Mì Ý Cá Hồi Xốt Kem Nấm", price: 78000, img: "img/menu/fries_014.jpg" },
            { id: "fries_015", name: "Salad Tôm Bơ", price: 97000, img: "img/menu/fries_015.jpg" },
            { id: "fries_016", name: "Salad Gà Nướng", price: 68000, img: "img/menu/fries_016.jpg" },
            { id: "fries_017", name: "Salad Trái Cây Nhiệt Đới", price: 60000, img: "img/menu/fries_017.jpg" },
            // Thêm các món khác vào đây
        ]
    },
    "heypelo": {
        name: "Hey! Pelo - Tacos Pháp",
        address: "11 Hẻm 94 Võ Oanh, Phường 25, Bình Thạnh, TP. HCM",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo2.jpg",
        bannerBg: "img/Background-shop/bg2.jpg", // Ảnh nền banner (nếu muốn thay đổi)
        menu: [
            { id: "pelo_001", name: "Tacos Size Mini", price: 80000, img: "img/menu/heypelo_001.jpg" },
            { id: "pelo_001", name: "Tacos Size Medium", price: 150000, img: "img/menu/heypelo_001.jpg" },
            { id: "pelo_001", name: "Tacos Size Large", price: 175000, img: "img/menu/heypelo_001.jpg" },
            { id: "pelo_002", name: "Khoai tây chiên giòn", price: 60000, img: "img/menu/heypelo_002.webp" },
            { id: "pelo_003", name: "Combo: Mini Pelo", price: 120000, img: "img/menu/heypelo_003.webp" },
            { id: "pelo_004", name: "Curry Pelo", price: 110000, img: "img/menu/heypelo_004.webp" },
            { id: "pelo_005", name: "K-Pelo", price: 110000, img: "img/menu/heypelo_005.webp" },
        ]
    },
    "comtam": {
        name: "Cơm Tấm Nguyễn Văn Cừ",
        address: "74 Nguyễn Văn Cừ, P. Nguyễn Cư Trinh, Quận 1, TP. Hồ Chí Minh ",
        rating: 4.6,
        time: "07:00 - 20:30",
        priceRange: "100,000đ - 150,000đ",
        logo: "img/Logo/logo3.png",
        bannerBg: "img/Background-shop/bg3.jpg",
        menu: [
            { id: "comtam_001", name: "Cơm Tấm Sườn Bì", price: 114000, img: "img/menu/comtam_001.png" },
            { id: "comtam_002", name: "Cơm Tấm Sườn Chả", price: 114000, img: "img/menu/comtam_002.png" },
            { id: "comtam_003", name: "Cơm Tấm Sườn Lạp Xưởng", price: 119000, img: "img/menu/comtam_003.png" },
            { id: "comtam_004", name: "Cơm Tấm Sườn Trứng", price: 114000, img: "img/menu/comtam_004.png" },
            { id: "comtam_005", name: "Cơm Tấm Sườn Que Bì", price: 124000, img: "img/menu/comtam_005.png" },
            { id: "comtam_006", name: "Cơm Tấm Sườn Que Chả", price: 124000, img: "img/menu/comtam_006.png" },
            { id: "comtam_007", name: "Cơm Tấm Sườn Que Trứng", price: 119000, img: "img/menu/comtam_007.png" },
            { id: "comtam_008", name: "Cơm Tấm Sườn Que Lạp Xưởng", price: 129000, img: "img/menu/comtam_008.png" },
            { id: "comtam_009", name: "Cơm Tấm Ba Chỉ Bì", price: 114000, img: "img/menu/comtam_009.png" },
            { id: "comtam_010", name: "Cơm Tấm Ba Chỉ Chả", price: 114000, img: "img/menu/comtam_010.png" },
            { id: "comtam_011", name: "Cơm Tấm Đùi Gà Bì", price: 114000, img: "img/menu/comtam_011.png" },
            { id: "comtam_012", name: "Cơm Tấm Đùi Gà Chả", price: 114000, img: "img/menu/comtam_012.png" },
            { id: "comtam_013", name: "Cơm Tấm Đùi Gà Trứng", price: 109000, img: "img/menu/comtam_013.png" },
            { id: "comtam_014", name: "Cơm Tấm Đùi Gà Lạp Xưởng", price: 119000, img: "img/menu/comtam_014.png" },
        ]
    },
    "banhmi": {
        name: "Bánh Mì Bà Huynh",
        address: "197A Nguyễn Trãi, P. Cầu Ông Lãnh, Quận 1, TP. Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo4.png",
        bannerBg: "img/Background-shop/bg4.png",
        menu: [
            { id: "banhmi_001", name: "Bánh mì đặc biệt size lướn", price: 100000, img: "img/menu/banhmi_001.webp" },
            { id: "banhmi_002", name: "Bánh mì đặc biệt size nhỏ 2/3", price: 75000, img: "img/menu/banhmi_001.webp" },
            { id: "banhmi_003", name: "Bánh mì nem nướng", price: 95000, img: "img/menu/banhmi_001.webp" },
            { id: "banhmi_004", name: "Bánh mì thịt pate bơ chà bông", price: 95000, img: "img/menu/banhmi_001.webp" },
            { id: "banhmi_005", name: "Bánh Mì Xíu Mại", price: 90000, img: "img/menu/banhmi_001.webp" },
            { id: "banhmi_006", name: "Xôi mặn", price: 50000, img: "img/menu/banhmi_002.webp" },
            { id: "banhmi_007", name: "Bánh bao đặc biệt", price: 30000, img: "img/menu/banhmi_003.jpg" },
            { id: "banhmi_008", name: "Bánh dày kẹp chả (2 cặp)", price: 36000, img: "img/menu/banhmi_004.jpg" },
            { id: "banhmi_009", name: "Xôi khúc nhân thịt", price: 26000, img: "img/menu/banhmi_005.jpg" },
        ]
    },
    "phuclong": {
        name: "Phúc Long",
        address: "734 Kha Vạn Cân, khu phố 5 P. Linh Trung TP. Thủ Đức TP. Hồ Chí Minh",
        rating: 4.9,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo5.png",
        bannerBg: "img/Background-shop/bg5.jpg",
        menu: [
            { id: "phuclong_001", name: "Trà Sữa Phúc Long (L)", price: 59000, img: "img/menu/phuclong_001.png" },
            { id: "phuclong_002", name: "Trà Sữa Ô Long Quế Hoa (L)", price: 55000, img: "img/menu/phuclong_002.png" },
            { id: "phuclong_003", name: "Trà Sữa Socola (M)", price: 55000, img: "img/menu/phuclong_003.png" },
            { id: "phuclong_004", name: "Hồng Trà Sữa (L)", price: 55000, img: "img/menu/phuclong_004.png" },
            { id: "phuclong_005", name: "Trà Vãi Lài (L)", price: 65000, img: "img/menu/phuclong_005.png" },
            { id: "phuclong_006", name: "Trà Nhãn Sen (L)", price: 65000, img: "img/menu/phuclong_006.png" },
            { id: "phuclong_007", name: "Hồng Trà Chanh (L)", price: 49000, img: "img/menu/phuclong_007.png" },
            { id: "phuclong_008", name: "Trà Phúc Long Kem Silky (L)", price: 59000, img: "img/menu/phuclong_008.png" },
            { id: "phuclong_009", name: "Trà Ô Long Kem Silky", price: 59000, img: "img/menu/phuclong_009.png" },
            { id: "phuclong_010", name: "Cà Phê Sữa Đá (M)", price: 39000, img: "img/menu/phuclong_010.png" },
        ]
    },
    "koi": {
        name: "Koi Thé",
        address: "372 Đ. Võ Văn Ngân,P. Bình Thọ, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.7,
        time: "09:00 - 22:00",
        priceRange: "80,000đ - 110,000đ",
        logo: "img/Logo/logo6.jpg",
        bannerBg: "img/Background-shop/bg6.png",
        menu: [
            { id: "koi_001", name: "Trà sữa khoai môn viên - Size M", price: 88000, img: "img/menu/koi_001.webp" },
            { id: "koi_002", name: "Trà sữa 3 loại topping mix - Size M (trân châu, khoai môn viên, thạch konjac)", price: 88000, img: "img/menu/koi_002.webp" },
            { id: "koi_003", name: "TRÀ SỮA KIỀU MẠCH TRÂN CHÂU HOÀNG KIM - size M", price: 79000, img: "img/menu/koi_003.webp" },
            { id: "koi_004", name: "Trà sữa trân châu hoàng kim - Size M", price: 79000, img: "img/menu/koi_004.webp" },
            { id: "koi_005", name: "Sữa tươi trân châu đường đen - Size M", price: 105000, img: "img/menu/koi_005.webp" },
            { id: "koi_006", name: "Trà sữa sương sáo - Size M", price: 84000, img: "img/menu/koi_006.webp" },
            { id: "koi_007", name: "HOT Brown Sugar Fresh Milk", price: 100000, img: "img/menu/koi_007.webp" },
            { id: "koi_008", name: "HOT Green Milk Tea", price: 74000, img: "img/menu/koi_008.webp" },
            { id: "koi_009", name: "HOT Green Milk Tea Macchiato", price: 88000, img: "img/menu/koi_009.webp" },
            { id: "koi_010", name: "HOT Brown Sugar Milk Tea", price: 84000, img: "img/menu/koi_010.webp" },
        ]
    },
    "TLJ": {
        name: "TOUS les JOURS",
        address: "A0103 Tòa Nhà T5, Masteri, 159 Xa Lộ Hà Nội, P. Thảo Điền, Tp. Thủ Đức, TP. HCM",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "39,000đ - 270,000đ",
        logo: "img/Logo/logo7.jpg",
        bannerBg: "img/Background-shop/bg7.jpg",
        menu: [
            { id: "tlj_001", name: "Snow Reindeer Yogurt Bread", price: 39000, img: "img/menu/tlj_001.webp" },
            { id: "tlj_002", name: "Lucky Wreath Bread", price: 42000, img: "img/menu/tlj_002.webp" },
            { id: "tlj_003", name: "Merry Santa’s Strawberry Yogurt Bread", price: 39000, img: "img/menu/tlj_003.webp" },
            { id: "tlj_004", name: "Cozy Christmas Pistachio Bread", price: 39000, img: "img/menu/tlj_004.webp" },
            { id: "tlj_005", name: "Cozy Original Tiramisu Mousse Box", price: 270000, img: "img/menu/tlj_005.webp" },
            { id: "tlj_006", name: "Cozy Cookies & Cheese Mousse Box", price: 270000, img: "img/menu/tlj_006.webp" },
            { id: "tlj_007", name: "Cozy Matcha Tiramisu Mousse Box", price: 270000, img: "img/menu/tlj_007.webp" },
            { id: "tlj_008", name: "Matcha Strawberry Latte", price: 60000, img: "img/menu/tlj_008.webp" },
            { id: "tlj_009", name: "Oat Milk Matcha latte - Matcha Sữa Yến Mạch", price: 65000, img: "img/menu/tlj_009.webp" },
            { id: "tlj_010", name: "Oat Milk Cafe Latte - Cà phê Latte Sữa Yến Mạch", price: 70000, img: "img/menu/tlj_010.webp" },
        ]
    },
    "PB": {
        name: "Paris Baguette",
        address: "TTTM Thiso Mall Sala, 8 - 10 Mai Chí Thọ, Thủ Đức, Thành phố Hồ Chí Minh 71110",
        rating: 4.6,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo8.jpg",
        bannerBg: "img/Background-shop/bg8.jpg",
        menu: [
            { id: "pb_001", name: "X-Mas Pastry Cube Set", price: 199000, img: "img/menu/pb_001.webp" },
            { id: "pb_002", name: "Bánh Choco Macaron", price: 40000, img: "img/menu/pb_002.webp" },
            { id: "pb_003", name: "Bánh mì Pineapple Cranberry Pastry", price: 40000, img: "img/menu/pb_003.webp" },
            { id: "pb_004", name: "Bánh Ham & Cheese Pastry Wrap Sandwich", price: 90000, img: "img/menu/pb_004.webp" },
            { id: "pb_005", name: "Bánh Soft Strawberry Cheesecake", price: 350000, img: "img/menu/pb_005.webp" },
            { id: "pb_006", name: "Fresh Cream Castella", price: 90000, img: "img/menu/pb_006.webp" },
            { id: "pb_007", name: "Bánh kem Tiramisu castella", price: 90000, img: "img/menu/pb_007.webp" },
            { id: "pb_008", name: "Happy puppy (short)", price: 70000, img: "img/menu/pb_008.webp" },
            { id: "pb_009", name: "Black Forest Cake (Slice)", price: 70000, img: "img/menu/pb_009.webp" },
            { id: "pb_010", name: "Fresh Cream Cake (Sliced)", price: 70000, img: "img/menu/pb_010.webp" },
            { id: "pb_011", name: "Fresh Choco Cream Cake (Sliced)", price: 70000, img: "img/menu/pb_011.webp" },
            { id: "pb_012", name: "Tiramisu Cheesecake (Slice)", price: 70000, img: "img/menu/pb_012.webp" },
            { id: "pb_013", name: "Blueberry Yogurt Cake (Sliced)", price: 70000, img: "img/menu/pb_013.webp" },
            { id: "pb_014", name: "Paris Rocher (Short)", price: 80000, img: "img/menu/pb_014.webp" },
        ]
    },
    "burger": {
        name: "Burger King",
        address: "1 Đ. Tân Hòa 2, Phường Tân Phú, Quận 9, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo9.png",
        bannerBg: "img/Background-shop/bg9.jpg",
        menu: [
            { id: "burger_001", name: "COUPLE SAVER 01", price: 139000, img: "img/menu/burger_001.jpg" },
            { id: "burger_002", name: "COUPLE SAVER 02", price: 179000, img: "img/menu/burger_002.jpg" },
            { id: "burger_003", name: "COUPLE SAVER 03", price: 149000, img: "img/menu/burger_003.jpg" },
            { id: "burger_004", name: "FAMILY PARTY", price: 289000, img: "img/menu/burger_004.jpg" },
            { id: "burger_005", name: "BURGER SURF N TURF", price: 149000, img: "img/menu/burger_005.jpg" },
            { id: "burger_006", name: "BURGER WHOPPER JR", price: 59000, img: "img/menu/burger_006.jpg" },
            { id: "burger_007", name: "DOUBLE EXTREME CHEESE WHOPPER", price: 109000, img: "img/menu/burger_007.jpg" },
            { id: "burger_008", name: "COMBO CHICKEN BBQ 2PCS", price: 105000, img: "img/menu/burger_008.jpg" },
            { id: "burger_009", name: "COMBO CHICKEN BBQ 3PCS", price: 125000, img: "img/menu/burger_009.jpg" },
            { id: "burger_010", name: "BBQ MIX WINGS 2PCS RICE COMBO", price: 64000, img: "img/menu/burger_010.jpg" },
            { id: "burger_011", name: "KHOAI TÂY CHIÊN SIZE M", price: 29000, img: "img/menu/burger_011.jpg" },
            { id: "burger_012", name: "KHOAI TÂY TẮM PHÔ MAI THỊT XÔNG KHÓI", price: 55000, img: "img/menu/burger_012.jpg" },
            { id: "burger_013", name: "PHÔ MAI QUE 8PCS", price: 89000, img: "img/menu/burger_013.jpg" },
            { id: "burger_014", name: "COCA", price: 25000, img: "img/menu/burger_014.jpg" },
            { id: "burger_015", name: "SPRITE", price: 25000, img: "img/menu/burger_015.jpg" },
        ]
    },
    "texas": {
        name: "Texas Chicken",
        address: "13 Đ. Võ Văn NgânLinh Chiểu, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.9,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo10.jpg",
        bannerBg: "img/Background-shop/bg10.png",
        menu: [
            { id: "texas_001", name: "Combo 11 Miếng Gà", price: 299000, img: "img/menu/texas_001.webp" },
            { id: "texas_002", name: "Set Tứ Vị Gà", price: 137000, img: "img/menu/texas_002.webp" },
            { id: "texas_003", name: "Combo Ghiền Bơ Tỏi & Thảo Mộc – Tặng 01 Bánh Mỳ Bơ Tỏi", price: 209000, img: "img/menu/texas_003.webp" },
            { id: "texas_004", name: "Combo 04 Miếng Gà Sốt Bơ Tỏi Và Thảo Mộc", price: 219000, img: "img/menu/texas_004.webp" },
            { id: "texas_005", name: "3 Miếng Gà Sốt Bơ Tỏi Và Thảo Mộc", price: 139000, img: "img/menu/texas_005.webp" },
            { id: "texas_006", name: "Combo 06 Miếng Gà Rán Truyền Thống", price: 359000, img: "img/menu/texas_006.webp" },
            { id: "texas_007", name: "Combo Gà Rán & Bánh cuộn Zesty Crunch", price: 119000, img: "img/menu/texas_007.webp" },
            { id: "texas_008", name: "Combo Bánh cuộn Tex", price: 89000, img: "img/menu/texas_008.webp" },
            { id: "texas_009", name: "Combo 03 Miếng Gà Giòn Không Xương", price: 79000, img: "img/menu/texas_009.webp" },
            { id: "texas_010", name: "01 Burger Gà Sốt Bơ Tỏi & Thảo Mộc", price: 59000, img: "img/menu/texas_010.webp" },
            { id: "texas_011", name: "Combo Burger Tex Supreme", price: 89000, img: "img/menu/texas_011.webp" },
            { id: "texas_012", name: "Khoai tây nghiền", price: 45000, img: "img/menu/texas_012.webp" },
            { id: "texas_013", name: "Bắp cải trộnS", price: 45000, img: "img/menu/texas_013.webp" },
            { id: "texas_014", name: "Khoai tây chiên phô mai", price: 49000, img: "img/menu/texas_014.webp" },
            { id: "texas_015", name: "Nước ngọt Coca-Cola", price: 27000, img: "img/menu/texas_015.webp" },
        ]
    },
    "ramen": {
        name: "Kohaku Ramen",
        address: "Vincom, 216 Đ. Võ Văn Ngân, Bình Thọ, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.7,
        time: "09:00 - 22:00",
        priceRange: "19,000đ - 150,000đ",
        logo: "img/Logo/logo11.jpg",
        bannerBg: "img/Background-shop/bg11.jpg",
        menu: [
            { id: "ramen_001", name: "Tonkotsu Ramen Mini", price: 93000, img: "img/menu/ramen_001.webp" },
            { id: "ramen_002", name: "Tonkotsu Ramen", price: 119000, img: "img/menu/ramen_002.webp" },
            { id: "ramen_003", name: "Kuro Tonkotsu Ramen", price: 130000, img: "img/menu/ramen_003.webp" },
            { id: "ramen_004", name: "Rayu Tonkotsu Ramen", price: 123000, img: "img/menu/ramen_004.webp" },
            { id: "ramen_005", name: "Rayu Kuro Tonkotsu Ramen", price: 135000, img: "img/menu/ramen_005.webp" },
            { id: "ramen_006", name: "Shoyu Ramen", price: 118000, img: "img/menu/ramen_006.webp" },
            { id: "ramen_007", name: "Rayu Soboro Tonkotsu Ramen", price: 123000, img: "img/menu/ramen_007.webp" },
            { id: "ramen_008", name: "Udon Bò (Size S)", price: 73000, img: "img/menu/ramen_008.webp" },
            { id: "ramen_009", name: "Udon Bò Trứng (Size M)", price: 110000, img: "img/menu/ramen_009.webp" },
            { id: "ramen_010", name: "Udon Bò Cay Trứng", price: 99000, img: "img/menu/ramen_010.webp" },
            { id: "ramen_011", name: "Set Gyoza + Nước", price: 61000, img: "img/menu/ramen_011.webp" },
            { id: "ramen_012", name: "Set Chicken Karaage + Nước", price: 73000, img: "img/menu/ramen_012.webp" },
            { id: "ramen_013", name: "Osen Tamago", price: 12000, img: "img/menu/ramen_013.webp" },
            { id: "ramen_014", name: "Kim Chi", price: 19000, img: "img/menu/ramen_014.webp" },
            { id: "ramen_015", name: "Pepsi (Lon)", price: 25000, img: "img/menu/ramen_015.webp" },
            { id: "ramen_016", name: "Pepsi Không Calo (Lon)", price: 25000, img: "img/menu/ramen_016.webp" },
            { id: "ramen_017", name: "Trà Oolong Tea+ (Plus) Không Đường (Chai)", price: 25000, img: "img/menu/ramen_017.webp" },
        ]
    },
    "pizza": {
        name: "Pizza 4P's",
        address: "TTTM Vincom Mega Mall Grand Park, Khu dân cư và công viên, Phước Thiện, Long Bình, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "60,000đ - 150,000đ",
        logo: "img/Logo/logo12.jpg",
        bannerBg: "img/Background-shop/bg12.jpg",
        menu: [
            { id: "pizza_001", name: "Pizza Phô mai Burrata Margherita thịt nguội", price: 398000, img: "img/menu/pizza_001.webp" },
            { id: "pizza_002", name: "Pizza 4 loại phô mai nhà làm", price: 248000, img: "img/menu/pizza_002.webp" },
            { id: "pizza_003", name: "Pizza 5 loại phô mai nhà làm", price: 298000, img: "img/menu/pizza_003.webp" },
            { id: "pizza_004", name: "Pizza Margherita với xúc xích Ý Milano và xúc xích cay Chorizo", price: 238000, img: "img/menu/pizza_004.webp" },
            { id: "pizza_005", name: "Pizza Gà xốt Teriyaki", price: 218000, img: "img/menu/pizza_005.webp" },
            { id: "pizza_006", name: "Mì Ý xốt kem với cua và xốt cà chua", price: 254000, img: "img/menu/pizza_006.webp" },
            { id: "pizza_007", name: "Gà rán gia vị phương Đông với xốt ớt Jalapeño nhà làm (2 miếng)", price: 98000, img: "img/menu/pizza_007.webp" },
            { id: "pizza_008", name: "Mì Ý bò bằm và phô mai hun khói nhà làm", price: 168000, img: "img/menu/pizza_008.webp" },
            { id: "pizza_009", name: "Phô mai Burrata kèm thịt nguội và trái cây nhiệt đới Salad (nhỏ)", price: 129000, img: "img/menu/pizza_009.webp" },
            { id: "pizza_010", name: "Mì Lasagna đút lò kèm phô mai Mozzarella nhà làm", price: 178000, img: "img/menu/pizza_010.webp" },
            { id: "pizza_011", name: "Phô mai Burrata kèm thịt nguội và trái cây nhiệt đới Salad (lớn)", price: 238000, img: "img/menu/pizza_011.webp" },
            { id: "pizza_012", name: "Salad tôm và bơ", price: 115000, img: "img/menu/pizza_012.webp" },
            { id: "pizza_013", name: "Sữa chua kiểu Hy Lạp (90g)", price: 40000, img: "img/menu/pizza_013.webp" },
            { id: "pizza_014", name: "Pudding kem trứng (90g)", price: 36000, img: "img/menu/pizza_014.webp" },
            { id: "pizza_015", name: "Bánh phô mai kép", price: 75000, img: "img/menu/pizza_015.webp" },
            { id: "pizza_016", name: "Coca-Cola Không Đường (Lon)", price: 25000, img: "img/menu/pizza_016.webp" },
        ]
    },
    "highland": {
        name: "Highlands Coffee",
        address: "Linh Trung 1, Quốc Lộ 1A, Linh Trung Ward , Thu Duc District, Ho Chi Minh City",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "19,000đ - 147,000đ",
        logo: "img/Logo/logo13.jpg",
        bannerBg: "img/Background-shop/bg13.jpg",
        menu: [
            { id: "highland_001", name: "Combo Sáng Highlands 45K", price: 45000, img: "img/menu/highland_001.webp" },
            { id: "highland_002", name: "Combo Sáng Highlands 63K", price: 63000, img: "img/menu/highland_002.webp" },
            { id: "highland_003", name: "Trà Sữa Đài Loan", price: 65000, img: "img/menu/highland_003.webp" },
            { id: "highland_004", name: "Combo Trà Chiều Highlands (1 Người)", price: 83000, img: "img/menu/highland_004.webp" },
            { id: "highland_005", name: "Trà Sữa Hồng Kông", price: 65000, img: "img/menu/highland_005.webp" },
            { id: "highland_006", name: "Combo Trà Chiều Highlands (Nhóm)", price: 147000, img: "img/menu/highland_006.webp" },
            { id: "highland_007", name: "Combo Tỉnh Táo 67K", price: 67000, img: "img/menu/highland_007.webp" },
            { id: "highland_008", name: "Trà Sữa Hojicha", price: 65000, img: "img/menu/highland_008.webp" },
            { id: "highland_009", name: "Mua 1 Freeze tặng 1 Trà Sữa", price: 75000, img: "img/menu/highland_009.webp" },
            { id: "highland_010", name: "Trà Sữa Trà Xanh", price: 65000, img: "img/menu/highland_010.webp" },
            { id: "highland_011", name: "Bánh Mì Que Gà Phô Mai", price: 19000, img: "img/menu/highland_011.webp" },
            { id: "highland_012", name: "Bánh Mì Que Pate", price: 19000, img: "img/menu/highland_012.webp" },
            { id: "highland_013", name: "Mousse Cacao", price: 35000, img: "img/menu/highland_013.webp" },
            { id: "highland_014", name: "Bánh Cuộn Vị Quế", price: 49000, img: "img/menu/highland_014.webp" },
            { id: "highland_015", name: "Bánh Phô Mai Chanh Dây Highlands", price: 35000, img: "img/menu/highland_015.webp" },
            { id: "highland_016", name: "Bánh Tiramisu Highlands", price: 39000, img: "img/menu/highland_016.webp" },
            { id: "highland_017", name: "Bánh Croissant Sô Cô La", price: 40000, img: "img/menu/highland_017.webp" },
        ]
    },
    "toco": {
        name: "TOCO TOCO",
        address: "184 Nguyễn Văn Tăng, Long Thạnh Mỹ, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "19,000đ - 150,000đ",
        logo: "img/Logo/logo14.jpg",
        bannerBg: "img/Background-shop/bg14.jpg",
        menu: [
            { id: "toco_001", name: "Xanh Sữa Nhài Năng Nổ", price: 30000, img: "img/menu/toco_001.jpg" },
            { id: "toco_002", name: "Xanh Nhài Mận Năng Nổ", price: 30000, img: "img/menu/toco_002.jpg" },
            { id: "toco_003", name: "Oolong Mộc Sen Kem Phô Mai", price: 65000, img: "img/menu/toco_003.jpg" },
            { id: "toco_004", name: "Trà Sữa Hạnh Phúc", price: 83000, img: "img/menu/toco_004.jpg" },
            { id: "toco_005", name: "Trà Sữa Đậu Đỏ", price: 65000, img: "img/menu/toco_005.jpg" },
            { id: "toco_006", name: "Chiến Thần Topping Khổng Lồ", price: 147000, img: "img/menu/toco_006.jpg" },
            { id: "toco_007", name: "Xanh Nhài Vải Quế Hoa", price: 67000, img: "img/menu/toco_007.jpg" },
            { id: "toco_008", name: "Trà Sữa Hai Anh Em", price: 65000, img: "img/menu/toco_008.jpg" },
            { id: "toco_009", name: "Ô Long Vải Quế Hoa", price: 75000, img: "img/menu/toco_009.jpg" },
            { id: "toco_010", name: "Xanh Nhài Vải Kem Phô Mai", price: 65000, img: "img/menu/toco_010.jpg" },
            { id: "toco_011", name: "Trà Xanh Chanh Leo Kem Phô Mai", price: 19000, img: "img/menu/toco_011.jpg" },
            { id: "toco_012", name: "Trà Sữa Khoai Môn Đường Hổ", price: 19000, img: "img/menu/toco_012.jpg" },
            { id: "toco_013", name: "Trà Xanh Đào Chanh Leo", price: 35000, img: "img/menu/toco_013.jpg" },
            { id: "toco_014", name: "Ô Long Đào Tiên", price: 49000, img: "img/menu/toco_014.jpg" },
            { id: "toco_015", name: "Bánh Phô Mai Chanh Dây Highlands", price: 35000, img: "img/menu/toco_015.jpg" },
            { id: "toco_016", name: "Bánh Tiramisu Highlands", price: 39000, img: "img/menu/toco_016.jpg" },
            { id: "toco_017", name: "Bánh Croissant Sô Cô La", price: 40000, img: "img/menu/toco_017.jpg" },
        ]
    },
    "sb": {
        name: "Starbucks",
        address: "Vinhomes Grand Park Origami, TP. Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "48,000đ - 150,000đ",
        logo: "img/Logo/logo15.jpg",
        bannerBg: "img/Background-shop/bg15.jpg",
        menu: [
            { id: "sb_001", name: "Iced Pure Matcha Latte", price: 102000, img: "img/menu/sb_001.webp" },
            { id: "sb_002", name: "Combo 2 ly Strawberry Acai with Lemonade Starbucks Refreshers™​ Beverage", price: 194000, img: "img/menu/sb_002.webp" },
            { id: "sb_003", name: "Iced Caramel Macchiato", price: 107000, img: "img/menu/sb_003.webp" },
            { id: "sb_004", name: "Salted Caramel Cold Foam Dolce Espresso", price: 87000, img: "img/menu/sb_004.webp" },
            { id: "sb_005", name: "Iced Caffè Americano", price: 87000, img: "img/menu/sb_005.webp" },
            { id: "sb_006", name: "Combo 2 ly Dolce Espresso", price: 144000, img: "img/menu/sb_006.webp" },
            { id: "sb_007", name: "Hot Caramel Macchiato", price: 107000, img: "img/menu/sb_007.webp" },
            { id: "sb_008", name: "Peppermint Mocha", price: 117000, img: "img/menu/sb_008.webp" },
            { id: "sb_009", name: "Iced Peppermint Mocha", price: 117000, img: "img/menu/sb_009.webp" },
            { id: "sb_010", name: "Peppermint Mocha Frappuccino® Blended Beverage", price: 122000, img: "img/menu/sb_010.webp" },
            { id: "sb_011", name: "Peppermint Chocolate Cream Frappuccino® Blended Beverage​", price: 122000, img: "img/menu/sb_011.webp" },
            { id: "sb_012", name: "Toffee Nut Crunch Latte", price: 117000, img: "img/menu/sb_012.webp" },
            { id: "sb_013", name: "Iced Toffee Nut Crunch Latte​", price: 117000, img: "img/menu/sb_013.webp" },
            { id: "sb_014", name: "Chocolate Croissant", price: 62000, img: "img/menu/sb_014.webp" },
            { id: "sb_015", name: "Banana Loaf", price: 48000, img: "img/menu/sb_015.webp" },
            { id: "sb_016", name: "Almond Croissants", price: 80000, img: "img/menu/sb_016.webp" },
            { id: "sb_017", name: "Bacon Cheese & Egg Croissant Bun", price: 100000, img: "img/menu/sb_017.webp" },
        ]
    },
    "boba": {
        name: "Bobapop - Taiwan Lattea",
        address: "Khu B Ký Túc Xá Làng Đại Học, Quốc lộ 1A, Linh Trung, Thủ Đức, TP. Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "48,000đ - 52,000đ",
        logo: "img/Logo/logo16.jpg",
        bannerBg: "img/Background-shop/bg16.jpg",
        menu: [
            { id: "boba_001", name: "Trà sữa Bobapop", price: 45000, img: "img/menu/boba_001.webp" },
            { id: "boba_002", name: "Trà sữa bạc hà", price: 48000, img: "img/menu/boba_002.webp" },
            { id: "boba_003", name: "Trà xanh kiwi", price: 52000, img: "img/menu/boba_003.webp" },
            { id: "boba_004", name: "Trà sữa mật ong", price: 48000, img: "img/menu/boba_004.webp" },
            { id: "boba_005", name: "Trà sữa vải", price: 45000, img: "img/menu/boba_005.webp" },
            { id: "boba_006", name: "Trà ô mai lắc đào", price: 55000, img: "img/menu/boba_006.webp" },
            { id: "boba_007", name: "Trà sữa đào", price: 42000, img: "img/menu/boba_007.webp" },
            { id: "boba_008", name: "Trà sữa Bá Tước", price: 48000, img: "img/menu/boba_008.webp" },
            { id: "boba_009", name: "Combo taichi", price: 42000, img: "img/menu/boba_009.webp" },
            { id: "boba_010", name: "Combo 3Q", price: 44000, img: "img/menu/boba_010.webp" },
            { id: "boba_011", name: "Combo 4Q​", price: 52000, img: "img/menu/boba_011.webp" },
            { id: "boba_012", name: "Hoa Lục Trà", price: 40000, img: "img/menu/boba_012.webp" },
            { id: "boba_013", name: "Trà bí đao​", price: 42000, img: "img/menu/boba_013.webp" },
            { id: "boba_014", name: "Trà sữa okinawa", price: 49000, img: "img/menu/boba_014.webp" },
            { id: "boba_015", name: "Trà bưởi", price: 52000, img: "img/menu/boba_015.webp" },
            { id: "boba_016", name: "Trà ô long sủi bọt", price: 47000, img: "img/menu/boba_016.webp" },
            { id: "boba_017", name: "Trà Bá Tước Sủi Bọt", price: 44000, img: "img/menu/boba_017.webp" },
        ]
    },
    "GongCha": {
        name: "Gong Cha",
        address: "32 Man Thiện, Hiệp Phú, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "48,000đ - 75,000đ",
        logo: "img/Logo/logo17.jpg",
        bannerBg: "img/Background-shop/bg17.jpg",
        menu: [
            { id: "gongcha_001", name: "TIRA-MINT-SU", price: 75000, img: "img/menu/gongcha_001.webp" },
            { id: "gongcha_002", name: "MINT COOKIES MILK TEA", price: 75000, img: "img/menu/gongcha_002.webp" },
            { id: "gongcha_003", name: "MINT MILK TEA", price: 78000, img: "img/menu/gongcha_003.webp" },
            { id: "gongcha_004", name: "Trà Sữa Trân Châu Đen", price: 51000, img: "img/menu/gongcha_004.webp" },
            { id: "gongcha_005", name: "Trà Sữa Khoai Môn", price: 59000, img: "img/menu/gongcha_005.webp" },
            { id: "gongcha_006", name: "Trà Sữa Oolong", price: 51000, img: "img/menu/gongcha_006.webp" },
            { id: "gongcha_007", name: "Trà Sữa Okinawa", price: 60000, img: "img/menu/gongcha_007.webp" },
            { id: "gongcha_008", name: "Trà Xanh Sữa Khoai Môn", price: 72000, img: "img/menu/gongcha_008.webp" },
            { id: "gongcha_009", name: "Sữa Tươi Okinawa", price: 55000, img: "img/menu/gongcha_009.webp" },
            { id: "gongcha_010", name: "Trà Sữa Okinawa Oreo", price: 60000, img: "img/menu/gongcha_010.webp" },
            { id: "gongcha_011", name: "Trà Sữa Xoài​", price: 65000, img: "img/menu/gongcha_011.webp" },
            { id: "gongcha_012", name: "Trà Khế Dừa Thạch Mật Ong", price: 68000, img: "img/menu/gongcha_012.webp" },
            { id: "gongcha_013", name: "Trà Khế Kem Sữa Thạch Mật Ong​", price: 72000, img: "img/menu/gongcha_013.webp" },
            { id: "gongcha_014", name: "Matcha Dừa Khế", price: 68000, img: "img/menu/gongcha_014.webp" },
            { id: "gongcha_015", name: "Matcha Warabi Mochi", price: 81000, img: "img/menu/gongcha_015.webp" },
            { id: "gongcha_016", name: "Okinawa Warabi Mochi", price: 81000, img: "img/menu/gongcha_016.webp" },
            { id: "gongcha_017", name: "Trà Oolong", price: 48000, img: "img/menu/gongcha_017.webp" },
        ]
    },
    "maycha": {
        name: "Trà Sữa MayCha",
        address: "TTTM Thiso Mall Sala, 8 - 10 Mai Chí Thọ, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "18,000đ - 40,000đ",
        logo: "img/Logo/logo18.jpg",
        bannerBg: "img/Background-shop/bg18.jpg",
        menu: [
            { id: "maycha_001", name: "Trà Sữa Đào Phô Mai", price: 40000, img: "img/menu/maycha_001.png" },
            { id: "maycha_002", name: "Lục Trà Sữa Song Hỷ Khoai Môn", price: 34000, img: "img/menu/maycha_002.png" },
            { id: "maycha_003", name: "Trà Sữa Mochi Triple Cheese", price: 39000, img: "img/menu/maycha_003.png" },
            { id: "maycha_004", name: "Hồng Trà Tắc", price: 19000, img: "img/menu/maycha_004.png" },
            { id: "maycha_005", name: "Trà Sữa Tiramisu", price: 32000, img: "img/menu/maycha_005.png" },
            { id: "maycha_006", name: "Trà Lài Mật Ong Váng Sữa", price: 32000, img: "img/menu/maycha_006.png" },
            { id: "maycha_007", name: "Trà Sữa Kem Trứng Khè", price: 33000, img: "img/menu/maycha_007.png" },
            { id: "maycha_008", name: "Trà Dâu Tây", price: 30000, img: "img/menu/maycha_008.png" },
            { id: "maycha_009", name: "Matcha Kem Trứng Khè", price: 39000, img: "img/menu/maycha_009.png" },
            { id: "maycha_010", name: "Hồng Trà Sữa Tây Côn Lĩnh", price: 27000, img: "img/menu/maycha_010.png" },
            { id: "maycha_011", name: "Trà Sữa SHAN Tuyết Lài​", price: 25000, img: "img/menu/maycha_011.png" },
            { id: "maycha_012", name: "Trà Lài Mật Ong Kem Trứng Khè", price: 32000, img: "img/menu/maycha_012.png" },
            { id: "maycha_013", name: "Trà Sữa Truyền Thống​", price: 25000, img: "img/menu/maycha_013.png" },
            { id: "maycha_014", name: "Trà Olong Tứ Quý", price: 18000, img: "img/menu/maycha_014.png" },
            { id: "maycha_015", name: "Trà Sữa Trân Châu Củ Năng", price: 27000, img: "img/menu/maycha_015.png" },
            { id: "maycha_016", name: "Trà Lựu Đỏ Thạch Dừa", price: 38000, img: "img/menu/maycha_016.png" },
            { id: "maycha_017", name: "Trà Chanh Thanh Xuân", price: 20000, img: "img/menu/maycha_017.png" },
        ]
    },
    "mixue": {
        name: "Trà Sữa Mixue",
        address: "KTX khu B ,Đông Hoà, Dĩ An, Bình Dương, Dĩ An",
        rating: 4.7,
        time: "09:00 - 22:00",
        priceRange: "19,000đ - 150,000đ",
        logo: "img/Logo/logo19.jpg",
        bannerBg: "img/Background-shop/bg19.jpg",
        menu: [
            { id: "mixue_001", name: "Super Sundae Socola", price: 25000, img: "img/menu/mixue_001.jpg" },
            { id: "mixue_002", name: "Super Sundae Trân Châu Đường Đen", price: 25000, img: "img/menu/mixue_002.jpg" },
            { id: "mixue_003", name: "Super Sundae Mâm Xôi", price: 25000, img: "img/menu/mixue_003.jpg" },
            { id: "mixue_004", name: "Super Sundae Dâu Tây", price: 25000, img: "img/menu/mixue_004.jpg" },
            { id: "mixue_005", name: "Sữa Kem Lắc Dâu Tây", price: 25000, img: "img/menu/mixue_005.jpg" },
            { id: "mixue_007", name: "Super Sundae Lô Hội", price: 25000, img: "img/menu/mixue_007.jpg" },
            { id: "mixue_008", name: "Super Sundae Xoài", price: 25000, img: "img/menu/mixue_008.jpg" },
            { id: "mixue_009", name: "Sữa Kem Lắc Đào", price: 25000, img: "img/menu/mixue_009.jpg" },
            { id: "mixue_010", name: "Hồng Trà Kem", price: 25000, img: "img/menu/mixue_010.jpg" },
            { id: "mixue_011", name: "Kem Cam Lốc Xoáy​", price: 25000, img: "img/menu/mixue_011.jpg" },
            { id: "mixue_012", name: "Trà Kem Bốn Mùa", price: 25000, img: "img/menu/mixue_012.jpg" },
            { id: "mixue_013", name: "Mixue chanh bạc bạc​", price: 25000, img: "img/menu/mixue_013.jpg" },
            { id: "mixue_014", name: "Tuyết Đỉnh Dâu Tây", price: 22000, img: "img/menu/mixue_014.jpg" },
            { id: "mixue_015", name: "Super Sundae Kiwi Dưa Lưới", price: 25000, img: "img/menu/mixue_015.jpg" },
            { id: "mixue_016", name: "Lucky Sundae O-coco", price: 25000, img: "img/menu/mixue_016.jpg" },
        ]
    },
    "cln": {
        name: "Cái Lò Nướng",
        address: "29 Lê Văn Việt, Hiệp Phú, TP Thủ Đức, TP. Hồ Chí Minh",
        rating: 4.7,
        time: "09:00 - 22:00",
        priceRange: "109,000đ - 695,000đ",
        logo: "img/Logo/logo20.jpg",
        bannerBg: "img/Background-shop/bg20.jpg",
        menu: [
            { id: "cln_001", name: "Seaweed Snack – Snack rong biển (150gram)", price: 120000, img: "img/menu/cln_001.jpg" },
            { id: "cln_002", name: "SWEETBOX SIGNATURE (Xanh) – Hộp 8 vị", price: 295000, img: "img/menu/cln_002.jpg" },
            { id: "cln_003", name: "SWEETBOX SIGNATURE (Xanh) – Hộp 16 bánh", price: 495000, img: "img/menu/cln_003.jpg" },
            { id: "cln_004", name: "Chocolate Dream Cake (Classic)", price: 225000, img: "img/menu/cln_004.jpg" },
            { id: "cln_005", name: "Tiralychée – Tiramisu Vải Mây", price: 625000, img: "img/menu/cln_005.jpg" },
            { id: "cln_007", name: "KoKo Mango – Entremet Xôi Xoài", price: 650000, img: "img/menu/cln_007.jpg" },
            { id: "cln_008", name: "Sweetin – Tiralychée (Premium)", price: 345000, img: "img/menu/cln_008.jpg" },
            { id: "cln_009", name: "SWEETBOX LOVE GARDEN PREMIUM", price: 695000, img: "img/menu/cln_009.jpg" },
            { id: "cln_010", name: "Sweetin – Chocolate Ruby Noel", price: 299000, img: "img/menu/cln_010.jpg" },
            { id: "cln_011", name: "Mangosteen Rose – Entremet Măng Cụt (màu Hồng)​", price: 750000, img: "img/menu/cln_011.jpg" },
            { id: "cln_012", name: "Hộp Bánh Chuối Sô-cô-laa", price: 109000, img: "img/menu/cln_012.jpg" },
            { id: "cln_013", name: "Garden Swan – Bánh Bắp Thiên Nga Trái Cây​", price: 615000, img: "img/menu/cln_013.jpg" },
            { id: "cln_014", name: "FESTI SWEETBOX – Hộp 16 bánh", price: 495000, img: "img/menu/cln_014.jpg" },
            { id: "cln_015", name: "Merry Matcha Berry – Bánh Matcha Dâu", price: 595000, img: "img/menu/cln_015.jpg" },
            { id: "cln_016", name: "Yule Log Red Velvet – Bánh Khúc Cây", price: 645000, img: "img/menu/cln_016.jpg" },
            { id: "cln_017", name: "Sweetin – Merry Misu", price: 285000, img: "img/menu/cln_017.jpg" },
        ]
    },
    "sugartown": {
        name: "Sugar Towns",
        address: "192 Đ. Võ Văn Ngân, Bình Thọ, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.7,
        time: "09:00 - 22:00",
        priceRange: "30,000đ - 480,000đ",
        logo: "img/Logo/logo21.jpg",
        bannerBg: "img/Background-shop/bg21.jpg",
        menu: [
            { id: "sugartown_001", name: "Tart Trứng Ngàn Lớp", price: 30000, img: "img/menu/sugartown_001.png" },
            { id: "sugartown_002", name: "Tart Phô Mai Chảy Vị Truyền Thống", price: 45000, img: "img/menu/sugartown_002.png" },
            { id: "sugartown_003", name: "Tart Phô Mai Chảy Vị Chocolate", price: 45000, img: "img/menu/sugartown_003.png" },
            { id: "sugartown_004", name: "Combo Mix Vị", price: 207000, img: "img/menu/sugartown_004.png" },
            { id: "sugartown_005", name: "Combo 2 Bánh Mì Phô Mai Tan Chảy", price: 207000, img: "img/menu/sugartown_005.png" },
            { id: "sugartown_007", name: "Sugar Mini Box-Tan Chảy Mix Vị", price: 60000, img: "img/menu/sugartown_007.png" },
            { id: "sugartown_008", name: "Burnt Lava Cheesecake", price: 150000, img: "img/menu/sugartown_008.png" },
            { id: "sugartown_009", name: "Matcha Burnt Lava Cheesecake", price: 150000, img: "img/menu/sugartown_009.png" },
            { id: "sugartown_010", name: "Bánh Kem Ốc", price: 20000, img: "img/menu/sugartown_010.png" },
            { id: "sugartown_011", name: "Bánh Choux Kem Truyền Thống​", price: 45000, img: "img/menu/sugartown_011.png" },
            { id: "sugartown_012", name: "Bánh Bông Lan Chà Bông Phô Mai Dẻo", price: 25000, img: "img/menu/sugartown_012.png" },
            { id: "sugartown_013", name: "Hộp quà tặng cookies Sugar Town​", price: 379000, img: "img/menu/sugartown_013.jpg" },
            { id: "sugartown_014", name: "Bánh Kem Socola Mẫu 1 size 18cm", price: 480000, img: "img/menu/sugartown_014.png" },
            { id: "sugartown_015", name: "Bánh Kem Socola Mẫu 2 size 18cm", price: 480000, img: "img/menu/sugartown_015.png" },
        ]
    },
    "hlm": {
        name: "Hỷ Lâm Môn",
        address: "S6.06, Vinhomes Grand Park, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "16,000đ - 552,000đ",
        logo: "img/Logo/logo22.jpg",
        bannerBg: "img/Background-shop/bg22.png",
        menu: [
            { id: "hlm_001", name: "Khúc cây Truyền thống KC TT X-MAS 25-01", price: 552500, img: "img/menu/hlm_001.png" },
            { id: "hlm_002", name: "Khúc cây Kim Quất KC KQ X-MAS 25-01", price: 552500, img: "img/menu/hlm_002.png" },
            { id: "hlm_003", name: "Tiramisu Douyin – Truyền thống", price: 65000, img: "img/menu/hlm_003.png" },
            { id: "hlm_004", name: "Tiramisu Douyin – Bạc Hà", price: 70000, img: "img/menu/hlm_004.png" },
            { id: "hlm_005", name: "Tiramisu Douyin – Nhãn Trà Thái", price: 70000, img: "img/menu/hlm_005.png" },
            { id: "hlm_006", name: "CHOCOLATE BỈ", price: 50000, img: "img/menu/hlm_006.png" },
            { id: "hlm_007", name: "BÔNG LAN TRỨNG MUỐI LY", price: 16000, img: "img/menu/hlm_007.png" },
            { id: "hlm_008", name: "BLACK AND WHITE", price:55000, img: "img/menu/hlm_008.png" },
            { id: "hlm_009", name: "PHOMAI HỘT GÀ", price: 260000, img: "img/menu/hlm_009.png" },
            { id: "hlm_010", name: "SU QUE LÁ DỨA MALAYSIA (06 CÂY/HỘP)", price: 40000, img: "img/menu/hlm_010.png" },
            { id: "hlm_011", name: "SU NHẬT​", price: 21000, img: "img/menu/hlm_011.png" },
            { id: "hlm_012", name: "BÔNG LAN TRỨNG MUỐI TÔ", price: 68000, img: "img/menu/hlm_012.png" },
            { id: "hlm_013", name: "SỮA TƯƠI TRÒN SÔ​", price: 45000, img: "img/menu/hlm_013.png" },
            { id: "hlm_014", name: "KEM BẮP MIẾNG", price: 45000, img: "img/menu/hlm_014.png" },
            { id: "hlm_015", name: "MOUSSE DÂU TẰM LY", price: 20000, img: "img/menu/hlm_015.png" },
            { id: "hlm_016", name: "MOUSSE CHANH DÂY LY", price: 20000, img: "img/menu/hlm_016.png" },
        ]
    },
    "givral": {
        name: "Givral Bakery",
        address: "121 Đ. Lê Văn Việt, Hiệp Phú, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "30,000đ - 480,000đ",
        logo: "img/Logo/logo23.jpg",
        bannerBg: "img/Background-shop/bg23.jpg",
        menu: [
            { id: "givral_001", name: "BÁNH PEACH CHEESE ENTREMET", price: 65000, img: "img/menu/givral_001.png" },
            { id: "givral_002", name: "BÁNH TART PHÔ MAI TRÂN CHÂU LEMON", price: 55000, img: "img/menu/givral_002.png" },
            { id: "givral_003", name: "BÁNH TART PHÔ MAI TRÂN CHÂU RASPBERRY", price: 55000, img: "img/menu/givral_003.png" },
            { id: "givral_004", name: "Tiramisu Pas", price: 68000, img: "img/menu/givral_004.png" },
            { id: "givral_005", name: "Oreo Cheese Cake", price: 75000, img: "img/menu/givral_005.png" },
            { id: "givral_006", name: "Black Forest", price: 75000, img: "img/menu/givral_006.png" },
            { id: "givral_007", name: "Moka Tròn", price: 55000, img: "img/menu/givral_007.png" },
            { id: "givral_008", name: "Blueberry Cheese", price:56000, img: "img/menu/givral_008.png" },
            { id: "givral_009", name: "Charlotte Exotique", price: 55000, img: "img/menu/givral_009.png" },
            { id: "givral_010", name: "Mint chocolate bavaroise", price: 52000, img: "img/menu/givral_010.png" },
            { id: "givral_011", name: "Capuchino Cake​", price: 57000, img: "img/menu/givral_011.png" },
            { id: "givral_012", name: "Pistachio Cherry Mousse", price: 56000, img: "img/menu/givral_012.png" },
            { id: "givral_013", name: "Opéra​", price: 44000, img: "img/menu/givral_013.png" },
            { id: "givral_014", name: "Bánh Bắp (M)", price: 48000, img: "img/menu/givral_014.png" },
            { id: "givral_015", name: "New York Cheese Cake", price: 58000, img: "img/menu/givral_015.jpg" },
            { id: "givral_016", name: "Chocolate Cheese", price: 58000, img: "img/menu/givral_016.jpg" },
        ]
    },
    "abc": {
        name: "ABC Bakery",
        address: "685 Đ. Lê Văn Việt, Long Thạnh Mỹ, Thủ Đức, Thành phố Hồ Chí Minh",
        rating: 4.8,
        time: "09:00 - 22:00",
        priceRange: "30,000đ - 480,000đ",
        logo: "img/Logo/logo24.jpg",
        bannerBg: "img/Background-shop/bg24.png",
        menu: [
            { id: "abc_001", name: "Brownie", price: 65000, img: "img/menu/abc_001.jpg" },
            { id: "abc_002", name: "Camsuachua", price: 200000, img: "img/menu/abc_002.jpg" },
            { id: "abc_003", name: "Cabybara", price: 150000, img: "img/menu/abc_003.jpg" },
            { id: "abc_004", name: "Cabybara Choco", price: 60000, img: "img/menu/abc_004.jpg" },
            { id: "abc_005", name: "Cupcake", price: 45000, img: "img/menu/abc_005.jpg" },
            { id: "abc_006", name: "Donut", price: 75000, img: "img/menu/abc_006.jpg" },
            { id: "abc_007", name: "Bông lan trứng muối", price: 55000, img: "img/menu/abc_007.jpg" },
            { id: "abc_008", name: "Croissant 2 màu", price:20000, img: "img/menu/abc_008.jpg" },
            { id: "abc_009", name: "Croissant Mini", price: 20000, img: "img/menu/abc_009.jpg" },
            { id: "abc_010", name: "Croissant thường", price: 20000, img: "img/menu/abc_010.jpg" },
            { id: "abc_011", name: "Mexico cà phê​", price:30000, img: "img/menu/abc_011.jpg" },
            { id: "abc_012", name: "Muffin Socola", price: 20000, img: "img/menu/abc_012.jpg" },
            { id: "abc_013", name: "Muffin Việt Quất​", price: 20000, img: "img/menu/abc_013.jpg" },
            { id: "abc_014", name: "Portuguese Egg Tart", price: 30000, img: "img/menu/abc_014.jpg" },
            { id: "abc_015", name: "Xúc xích đặc biệt", price: 15000, img: "img/menu/abc_015.jpg" },
            { id: "abc_016", name: "Bánh Kem", price: 25000, img: "img/menu/abc_016.jpg" },
        ]
    },
};